version: '3.8'

services:
  database:
    container_name: mongodb
    image: sourabhhbar/mongo
    command: mongod
    ports:
    - 27018:27017
    restart: always
    volumes:
    - mongodata:/data/db

  eureka-naming-server:
    image: sourabhhbar/eureka-naming-server
    container_name: eureka-naming-server
    restart: always
    ports:
    - 8761:8761
    depends_on:
      - database

  booking-service:
    image: sourabhhbar/booking-service
    container_name: booking-service
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-naming-server:8761/eureka
      - spring.data.mongodb.host=database
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=casestudy
    ports:
    - 8082:8082
    depends_on:
      - eureka-naming-server
    links:
      - eureka-naming-server
      - database

  hotel-service:
    image: sourabhhbar/hotel-service
    container_name: hotel-service
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-naming-server:8761/eureka
      - spring.data.mongodb.host=database
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=casestudy
    ports:
    - 8081:8081
    depends_on:
      - eureka-naming-server
    links:
      - eureka-naming-server
      - database
  demo-app-service:
    image: sourabhhbar/demo-app-service
    container_name: demo-app-service
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-naming-server:8761/eureka
      - spring.data.mongodb.host=database
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=casestudy
    ports:
    - 8083:8083
    depends_on:
      - eureka-naming-server
    links:
      - eureka-naming-server
      - database

networks:
  default:
    external:
      name: micro-net
volumes:
  mongodata:
    driver: local




#####################################
docker pull sourabhhbar/eureka-naming-server
docker pull sourabhhbar/booking-service
docker pull sourabhhbar/demo-app-service
docker pull sourabhhbar/hotel-service



